import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";
import { ApolloClient, gql, useQuery, InMemoryCache } from "@apollo/client";

const { GRAPHQL_SERVER } = process.env;

const client = new ApolloClient({
  uri: GRAPHQL_SERVER,
  cache: new InMemoryCache(),
});

const lightQuery = gql`
  query {
    currentData {
      illuminance {
        value
      }
    }
  }
`;

export default function Home({ init_data }) {
  const [light, setLight] = useState(
    init_data.data.currentData[0].illuminance[0].value
  );

  const { data, loading, error } = useQuery(lightQuery, {
    pollInterval: 100,
  });

  useEffect(() => {
    if (data != undefined) {
      setLight(data.currentData[0].illuminance[0].value);
    }
  }, [data]);

  if (loading) return null;
  if (error) return <p>ERROR</p>;
  if (!data) return <p>Not found</p>;

  return (
    <div className={styles.container}>
      <Head>
        <title>Atom Drone App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Atom Drone App</h1>
        <p className={styles.description}>Light value: </p>
        <p className={styles.description}> {light} </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getServerSideProps() {
  const init_data = await client.query({
    query: lightQuery,
    fetchPolicy: "no-cache",
  });

  // Pass data to the page via props
  return { props: { init_data } };
}
